var fontsDemoData = {
  "zeplinFonts": [{
    "zeplinFontName": "Lato",
    "fontVariations": {
      "thin": "Lato-HairLine",
      "extralight": "Lato",
      "light": "Lato-Light",
      "normal": "Lato-Regular",
      "medium": "Lato",
      "semibold": "Lato",
      "bold": "Lato-Bold",
      "extrabold": "Lato",
      "black": "Lato-Black"
    }
  }],
  "colors": [{
      "name": "$liteBlue",
      "color": "#0099ff"
    }, {
      "name": "$navyBlue",
      "color": "#0000FF"
    }, {
      "name": "$linkBlue",
      "color": "#3333FF"
    }, {
      "name": "$liteGray",
      "color": "#999999"
    }, {
      "name": "$lightgray",
      "color": "lightgray"
    }, {
      "name": "$dimLiteGray",
      "color": "#efefef"
    }, {
      "name": "$gray",
      "color": "#333333"
    }, {
      "name": "$skyBlue",
      "color": "#28aedd"
    }, {
      "name": "$orange",
      "color": "#fb5e00"
    }, {
      "name": "$blue",
      "color": "#015ddb"
    }, {
      "name": "$violet",
      "color": "#ab1763"
    }, {
      "name": "$white",
      "color": "#ffffff"
    }, {
      "name": "$liteBlue3",
      "color": "#0000FF"
    }, {
      "name": "$liteAsh1",
      "color": "#ddd"
    }, {
      "name": "$liteAsh2",
      "color": "#d8d8d8"
    }, {
      "name": "$liteAsh3",
      "color": "#e3e3e3"
    }, {
      "name": "$liteAsh4",
      "color": "#f4f4f4"
    }, {
      "name": "$litePink",
      "color": "#dbbde5"
    }, {
      "name": "$liteGreen",
      "color": "#b5efce"
    }, {
      "name": "$bluishGreen",
      "color": "#ace6e8"
    }, {
      "name": "$black",
      "color": "#000000"
    }, {
      "name": "$liteBlue2",
      "color": "#2c7aec"
    }, {
      "name": "$textLinkBlue",
      "color": " #00C3DE"
    }, {
      "name": "$liteAsh5",
      "color": "#0c3d6c"
    }, {
      "name": "$darkGray",
      "color": "#666666"
    }, {
      "name": "$bodyGrey",
      "color": " #f9fafb "
    }, {
      "name": "$breadGray",
      "color": "#555555"
    }, {
      "name": "$liteAsh7",
      "color": "#504c51"
    }, {
      "name": "$liteAsh8",
      "color": "#47585f"
    }, {
      "name": "$liteAsh6",
      "color": "#444444"
    }, {
      "name": "$liteGray2",
      "color": "#5a5a5a"
    }, {
      "name": "$deepRed",
      "color": "#fe424d"
    }, {
      "name": "$ashGrey",
      "color": "#95a0a9"
    }, {
      "name": "$liteBlue4",
      "color": "#eff4fb"
    }, {
      "name": "$darkRed",
      "color": "#ea2128"
    }, {
      "name": "$bluishGreen2",
      "color": "#68d2db"
    }, {
      "name": "$lightBlack",
      "color": "#191919"
    }, {
      "name": "$linkblue",
      "color": "#06447f"
    }, {
      "name": "$black1",
      "color": "rgba(0, 0, 0, 0.9)"
    }, {
      "name": "$black2",
      "color": "rgba(0, 0, 0, 0.6)"
    }, {
      "name": "$lightGray1",
      "color": "#d5dee4"
    }, {
      "name": "$skillSheetTileNewBg",
      "color": "#3498db"
    }, {
      "name": "$issueTileBgBlue",
      "color": "#eff5fc"
    }, {
      "name": "$issueGridButtonFontColor",
      "color": "#174877"
    }, {
      "name": "$lightGrey2",
      "color": "#606162"
    }, {
      "name": "$tabBgGrey",
      "color": "#e2e4e7"
    }, {
      "name": "$tabBgBlue",
      "color": "#00aeef"
    }, {
      "name": "$tabBgGreyText",
      "color": "#818387"
    }, {
      "name": "$globinpPlaceholdText",
      "color": "#00171f"
    }, {
      "name": "$globalNavExporeGray",
      "color": "#7c7c7c"
    }, {
      "name": "$contentTileSubjectBlue",
      "color": "#0054a6"
    }, {
      "name": "$titleHyperlinkColor",
      "color": "#00a6fb"
    }, {
      "name": "$emailSubjectFieldGrey",
      "color": "#777c81"
    }, {
      "name": "$requiredFieldstextGrey",
      "color": "#898989"
    }, {
      "name": "$errorFieldTextColor",
      "color": "#d60000"
    }, {
      "name": "$emailFormInputFontColor",
      "color": "#858585"
    }, {
      "name": "$textHyperlinkColor",
      "color": "#0083ca"
    }, {
      "name": "$commentFormDescText",
      "color": "#282828"
    }, {
      "name": "$commentLabelTextGrey",
      "color": "#595a5b"
    }, {
      "name": "$commentInputBorder",
      "color": "#d7d7d7"
    }, {
      "name": "$commentFormNoteText",
      "color": "#828282"
    }, {
      "name": "$commentHeadingBorderColor",
      "color": "#909090"
    }, {
      "name": "$marketingSubscriptionGrey",
      "color": "#110c0e"
    }, {
      "name": "$marketingSubscriptionLightGrey",
      "color": "#1e1d1e"
    }, {
      "name": "$marketingSubscriptionBorderGrey",
      "color": "#c8c8c8"
    },
    {
      "name": "$subscriptionTextGrey",
      "color": "#2b2a2b"
    }
  ]
};